version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "part: github_actions"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "lang: python"
      - "part: dependencies"

  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "monthly"
    labels:
      - "lang: javascript"
      - "part: dependencies"
