trigger:
- main

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: cd js; yarn
      displayName: "Install JS Dependencies"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      displayName: 'Install python dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script:
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'

- job: 'Mac'
  pool:
    vmImage: 'macos-10.14'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: cd js; yarn
      displayName: "Install JS Dependencies"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      displayName: 'Install python dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script: |
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: cd js; yarn
      displayName: "Install JS Dependencies"

    - script: |
        which python > python.txt
        set /p PYTHON=<python.txt
        ln -s %PYTHON% %PYTHON%$(python.version)
        python --version
        which python$(python.version)
      displayName: "Which python"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
      displayName: 'Install python dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script: |
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'
